# Site settings
title: The Future Labs Company
description: 'Artificial Intelligence trends and concepts made easy.' # this means to ignore newlines until "baseurl:"
permalink: ':title:output_ext'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://thefuturelabs.co" # the base hostname & protocol for your site, e.g. http://example.com
remote_theme: longpdo/neumorphism
username: The Future Labs Co